# Waveshare mmWave reuires 50mA power. 
# reference: https://www.waveshare.com/wiki/HMMD_mmWave_Sensor
# Bosche BME688 average power consumption during gas scaning is 3.9 mA
# reference: https://www.bosch-sensortec.com/products/environmental-sensors/gas-sensors/bme688/#technical
# version 2.31
proximity_check : 180000
enviro_update: 10
# reboot in case of memory leaks. 
reboot_cycle: 480
#
device : "Pimoroni PicoPlus2W/bme690"
station : "<STATION>"
#
mmwave:
    tx_pin : 26
    rx_pin : 27
    uart : 1
    baudrate: 115200
    scan_duration: 9000

# could be 0x76 or 0x77, enter decimal equivalent below. check device scanner printout to debug.
bme:
    i2c: 1
    i2c_adr: 118
    scan_duration: 11000
    temp_offset: 2.5
    heater_temp: 149
    heater_duration: 97
    sda: 4 
    scl: 5
    pwr_pin : 0
    
#ssd1306
oled:
    i2c: 1
    i2c_adr: 60
    width: 128
    height: 32
    sda: 18
    scl: 19
    pwr_pin: 22

wifi:
    ssid : "<SSID>"
    psk  : "<WIFI_PASSWORD>"
    country: "ca"
    retry: 5        
mqtt:
   broker : "io.adafruit.com"
   port: 8883
   uid : "ADAFRUIT_AIO_USERNAME"
   pwd : "ADAFRUIT_AIO_KEY"
   topic_motus: "<ADAFRUIT_AIO_USERNAME>/feeds/motus"
   topic_temp: "<ADAFRUIT_AIO_USERNAME>/feeds/<STATION>-slash-temperature"
   topic_pres: "<ADAFRUIT_AIO_USERNAME>/feeds/<STATION>-slash-pressure"
   topic_humd: "<ADAFRUIT_AIO_USERNAME>/feeds/<STATION>-slash-humidity"
   topic_voc:  "<ADAFRUIT_AIO_USERNAME>/feeds/<STATION>-slash-voc"
