{
 "title": "humblepi",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"memuse\", \"memfree\", \"time\", \"cacheuse\" FROM \"sensors\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"station\" = 'humblepi' "
    }
   ]
  },
  {
   "title": "cpu throttled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"throttled\", \"time\" FROM \"sensors\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"station\" = 'humblepi' "
    }
   ]
  },
  {
   "title": "cpu",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"time\", \"cpuusr\" AS \"usr\", \"cpunice\" AS \"nice\", \"cpusys\" AS \"sys\", \"cpuiowait\" AS \"iowait\", \"cpuirq\" AS \"irq\", \"cpusoft\" AS \"soft\", \"cpusteal\" AS \"steal\", \"cpugnice\" AS \"gnice\", \"cpuidle\" AS \"idle\" FROM \"sensors\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND (cpusys > 0 AND \"station\" = 'humblepi') "
    }
   ]
  },
  {
   "title": "cpu temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"temperature\", \"time\" FROM \"sensors\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"station\" = 'humblepi' "
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"diskavail\", \"diskused\" FROM \"sensors\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"station\" = 'humblepi' "
    }
   ]
  },
  {
   "title": "cpu voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"voltage\", \"time\" FROM \"sensors\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"station\" = 'humblepi' "
    }
   ]
  }
 ]
}